SoftwareTaller/clientes/urls.py
from . import views

from django.urls import path

urlpatterns = [
    #Menú de clientes
    path("", views.clientes, name="clientes"),
    #Registrar
    path("registrar_cliente/", views.registrar_cliente, name="registrar_cliente"),
    #Buscar
    path("buscar_clientes/", views.buscar_clientes, name="buscar_clientes"),
    #Editar
    path('obtener_registro_clientes/<int:cliente_id>/', views.obtener_registro_clientes, name='obtener_registro_clientes'),
    path("editar_cliente/", views.editar_cliente, name="editar_cliente"),
    #Eliminar
    path("eliminar_cliente/<int:id>", views.eliminar_cliente, name="eliminar_cliente"),
]

SoftwareTaller/inventario/urls.py
from . import views

from django.urls import path

urlpatterns = [
    #Menú de inventario
    path("", views.inventario, name="inventario"),
    #Registrar
    path("registrar_producto/", views.registrar_producto, name="registrar_producto"),
    #Buscar
    path("buscar_productos/", views.buscar_productos, name="buscar_productos"),
    #Editar
    path('obtener_registro_inventario/<int:producto_id>/', views.obtener_registro_inventario, name='obtener_registro_inventario'),
    path("editar_producto/", views.editar_producto, name="editar_producto"),
    #Eliminar
    path("eliminar_producto/<int:id>", views.eliminar_producto, name="eliminar_producto"),
]

SoftwareTaller/servicios/urls.py
from . import views

from django.urls import path

urlpatterns = [
    #Menú de servicios
    path("", views.servicios, name="servicios"),
    path("buscar_asignacion_cliente/", views.buscar_asignacion_cliente, name="buscar_asignacion_cliente"),
    path("buscar_asignacion_productos/", views.buscar_asignacion_productos, name="buscar_asignacion_productos"),
    #Registrar
    path("registrar_servicio/", views.registrar_servicio, name="registrar_servicio"),
    # path("formulario_registrar_servicios/registrado", views.formulario_registrar_servicios_registrado, name="formulario_registrar_servicios_registrado"),
    # #Buscar
    path("buscar_servicios/", views.buscar_servicios, name="buscar_servicios"),
    # #Editar
    path('obtener_registro_servicios/<int:servicio_id>/', views.obtener_registro_servicios, name='obtener_registro_servicios'),
    path("editar_servicio/", views.editar_servicio, name="editar_servicio"),
    # #Eliminar
    path("eliminar_servicio/<int:id>", views.eliminar_servicio, name="eliminar_servicio"),

]

SoftwareTaller/ventas/urls.py
from . import views

from django.urls import path

urlpatterns = [
    path("", views.inicio, name="inicio_ventas")
]

SoftwareTaller/clientes/models.py
from django.db import models

# Create your models here.

class Cliente(models.Model):
    nombre_cliente = models.CharField(max_length=50, null=False, blank=False)
    documento_identidad = models.CharField(max_length=20, null=False, blank=False)
    correo_electronico = models.EmailField(max_length=100, null=True, blank=True)
    telefono = models.CharField(max_length=15, null=True, blank=True)

SoftwareTaller/inventario/models.py
from django.db import models

# Create your models here.


class TipoProducto(models.Model):
    tipo = models.CharField(max_length=40, null=False, blank=False)

class Producto(models.Model):
    marca = models.CharField(max_length=60,null=False, blank=False)
    referencia = models.CharField(max_length=40, null=False, blank=False)
    tipo_producto = models.ForeignKey(TipoProducto, on_delete=models.PROTECT)
    precio = models.IntegerField(null=False, blank=False)
    unidades_disponibles = models.IntegerField(null=False, blank=False)

SoftwareTaller/servicios/models.py
from django.db import models
from django.utils import timezone
from clientes.models import Cliente
from inventario.models import Producto
# Create your models here.

class NombreServicio(models.Model):
    nombre_servicio = models.CharField(max_length=40, null=False, blank=False)

class Servicio(models.Model):
    nombre_servicio = models.ForeignKey(NombreServicio, on_delete=models.PROTECT)
    descripcion = models.CharField(max_length=200, null=True, blank=True)
    precio_adicional = models.IntegerField(default=0)
    costo_total = models.IntegerField(null=False, blank=False)
    fecha = models.DateField(default=timezone.now)
    cliente = models.ForeignKey(Cliente, on_delete=models.PROTECT)

class Servicio_Productos(models.Model):
    servicio = models.ForeignKey(Servicio, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.PROTECT)
    cantidad = models.IntegerField(default=1)

SoftwareTaller/clientes/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from .models import Cliente
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from django.db.models.deletion import ProtectedError
# Create your views here.

# MENÚ CLIENTES
@login_required
def clientes(request, clientes=None, registrado=False, eliminado=False, actualizado=False, sin_coincidencias=False, campo=None, buscar=None, error=False, mensaje_error=None, name_url="clientes"):
    if clientes is None:
        clientes = Cliente.objects.all()
    paginator = Paginator(clientes, 20)

    numero_pagina = request.GET.get('pagina')

    try:
        # Obtener la página solicitada
        pagina = paginator.page(numero_pagina)
    except PageNotAnInteger:
        # Si el número de página no es un entero, mostrar la primera página
        pagina = paginator.page(1)
    except EmptyPage:
        # Si la página está fuera de rango (página vacía), mostrar la última página
        pagina = paginator.page(paginator.num_pages)

    return render(request, 'clientes.html', {
        'registrado': registrado,
        "eliminado": eliminado,
        "actualizado": actualizado,
        "sin_coincidencias": sin_coincidencias,
        "buscar": buscar,
        "campo": campo,
        "pagina": pagina,
        "error": error,
        "mensaje_error": mensaje_error,
        "name_url": name_url,
    })

# REGISTRAR CLIENTES


## Recepción de formulario y creacion de registro
def registrar_cliente(request):
    try:
        nombre_cliente = request.POST['nombre_cliente']
        documento_identidad = request.POST['documento_identidad']
        correo_electronico = request.POST['correo_electronico']
        telefono = request.POST['telefono']

        if Cliente.objects.filter(documento_identidad=documento_identidad).exists():
            return clientes(request, error=True, mensaje_error="El número de DI que se desea registrar ya existe.")

        else:
            Cliente.objects.create(nombre_cliente=nombre_cliente, documento_identidad=documento_identidad, correo_electronico=correo_electronico, telefono=telefono)

            return clientes(request, registrado=True)
    except:
        return clientes(request, error=True, mensaje_error="No se está accediendo adecuadamente a la funcionalidad.")



# BUSCAR CLIENTES

def buscar_clientes(request):
    campo = request.GET['campo']
    buscar = request.GET['buscar']
    resultado = Cliente.objects.filter(**{f'{campo}__icontains': buscar})
    if (resultado.count()==0):
        no_coincidencias = True
    else:
        no_coincidencias = False
    return clientes(request, clientes=resultado, sin_coincidencias=no_coincidencias, campo=campo, buscar=buscar)



# EDITAR CLIENTES

## Vista que recibe el id y renderiza el formulario de edicion
def obtener_registro_clientes(request, cliente_id):
    cliente = Cliente.objects.get(id=cliente_id)
    datos_cliente = {
        'id': cliente.id,
        'nombre_cliente': cliente.nombre_cliente,
        'documento_identidad': cliente.documento_identidad,
        'correo_electronico': cliente.correo_electronico,
        'telefono': cliente.telefono
    }
    return JsonResponse(datos_cliente)

def editar_cliente(request):
    try:
        id = request.POST['registro_id']
        nombre_cliente = request.POST['nombre_cliente']
        documento_identidad = request.POST['documento_identidad']
        correo_electronico = request.POST['correo_electronico']
        telefono = request.POST['telefono']

        cliente = Cliente.objects.get(id=id)
        if (Cliente.objects.filter(documento_identidad=documento_identidad).exists()) and documento_identidad!=cliente.documento_identidad:
            return clientes(request, error=True, mensaje_error="El número de DI que se desea registrar ya existe en un registro diferente.")
        else:
            cliente.nombre_cliente = nombre_cliente
            cliente.documento_identidad = documento_identidad
            cliente.correo_electronico = correo_electronico
            cliente.telefono = telefono

            cliente.save()

            return clientes(request, actualizado=True)

    except:
        return clientes(request, error=True, mensaje_error="No se está accediendo adecuadamente a la funcionalidad.")


# ELIMINAR CLIENTES

## Vista que recibe el id y elimina el cliente de la base de datos
def eliminar_cliente(request, id):
    try:
        cliente = Cliente.objects.get(id=id)

        cliente.delete()
        return clientes(request, eliminado=True)
    except ProtectedError:
        return clientes(request, error=True, mensaje_error="El cliente tiene servicios asociados y no puede ser eliminado.")
    except:
        return clientes(request, error=True, mensaje_error="No se está accediendo adecuadamente a la funcionalidad.")

SoftwareTaller/inventario/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse, HttpResponse
from .models import Producto, TipoProducto
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from django.db.models.deletion import ProtectedError
# Create your views here.

# MENÚ INVENTARIO



@login_required
def inventario(request, productos=None, registrado=False, eliminado=False, actualizado=False, sin_coincidencias=False, campo=None, buscar=None, error=False, mensaje_error=None, name_url="inventario"):
    if productos is None:
        productos = Producto.objects.all()
    paginator = Paginator(productos, 20)

    numero_pagina = request.GET.get('pagina')

    try:
        # Obtener la página solicitada
        pagina = paginator.page(numero_pagina)
    except PageNotAnInteger:
        # Si el número de página no es un entero, mostrar la primera página
        pagina = paginator.page(1)
    except EmptyPage:
        # Si la página está fuera de rango (página vacía), mostrar la última página
        pagina = paginator.page(paginator.num_pages)

    tipos_productos = TipoProducto.objects.all()
    lista_tipos_productos = list(TipoProducto.objects.values())
    return render(request, 'inventario.html', {
        "registrado": registrado,
        "eliminado": eliminado,
        "actualizado": actualizado,
        "sin_coincidencias": sin_coincidencias,
        "buscar": buscar,
        "campo": campo,
        "pagina": pagina,
        "error": error,
        "mensaje_error": mensaje_error,
        "name_url": name_url,
        "tipos_productos": tipos_productos,
        "lista_tipos_productos": lista_tipos_productos,
    })

# REGISTRAR PRODUCTOS


## Recepción de formulario y creacion de registro
def registrar_producto(request):
    try:
        marca = request.POST['marca']
        referencia = request.POST['referencia']
        tipo_producto = request.POST['tipo_producto']
        precio = request.POST['precio']
        unidades_disponibles = request.POST['unidades_disponibles']
        seleccion_tipo_producto = TipoProducto.objects.get(id=tipo_producto)
        Producto.objects.create(marca=marca, referencia=referencia, tipo_producto=seleccion_tipo_producto, precio=precio, unidades_disponibles=unidades_disponibles)

        return inventario(request, registrado=True)
    except:
        return inventario(request, error=True, mensaje_error="No se está accediendo adecuadamente a la funcionalidad.")




# # BUSCAR PRODUCTOS

def buscar_productos(request):
    campo = request.GET['campo']
    buscar = request.GET['buscar']
    filtro = request.GET.get('filtro')

    if filtro == "menor_igual":
        resultado = Producto.objects.filter(**{f'{campo}__lte': buscar}).order_by('-' + campo)
    elif filtro == "mayor_igual":
        resultado = Producto.objects.filter(**{f'{campo}__gte': buscar}).order_by(campo)
    else:
        if campo == "tipo_producto":
            resultado = Producto.objects.filter(tipo_producto = buscar)
        else:
            resultado = Producto.objects.filter(**{f'{campo}__icontains': buscar})
    if (resultado.count()==0):
        no_coincidencias = True
    else:
        no_coincidencias = False
    return inventario(request, productos=resultado, sin_coincidencias=no_coincidencias, campo=campo, buscar=buscar)



# EDITAR PRODUCTOS

## Vista que recibe el id y renderiza el formulario de edicion

def obtener_registro_inventario(request, producto_id):
    producto = Producto.objects.get(id=producto_id)
    datos_producto = {
        'id': producto.id,
        'marca': producto.marca,
        'referencia': producto.referencia,
        'tipo_producto': producto.tipo_producto.id,
        'precio': producto.precio,
        'unidades_disponibles': producto.unidades_disponibles,
    }
    return JsonResponse(datos_producto)

def editar_producto(request):
    try:

        id = request.POST['registro_id']
        marca = request.POST['marca']
        referencia = request.POST['referencia']
        tipo_producto = request.POST['tipo_producto']
        precio = request.POST['precio']
        unidades_disponibles = request.POST['unidades_disponibles']

        seleccion_tipo_producto = TipoProducto.objects.get(id=tipo_producto)

        producto = Producto.objects.get(id=id)
        producto.marca = marca
        producto.referencia = referencia
        producto.tipo_producto = seleccion_tipo_producto
        producto.precio = precio
        producto.unidades_disponibles = unidades_disponibles

        producto.save()

        return inventario(request, actualizado=True)
    except:
        return inventario(request, error=True, mensaje_error="No se está accediendo adecuadamente a la funcionalidad.")




# ELIMINAR PRODUCTOS

## Vista que recibe el id y elimina el producto de la base de datos
def eliminar_producto(request, id):
    try:
        producto = Producto.objects.get(id=id)
        producto.delete()
        return inventario(request, eliminado=True)
    except ProtectedError:
        return inventario(request, error=True, mensaje_error="El producto está asociado a algún servicio y no puede ser eliminado.")
    except:
        return inventario(request, error=True, mensaje_error="No se está accediendo adecuadamente a la funcionalidad.")

SoftwareTaller/templates/clientes.html
{% extends "layouts/base.html" %}
{% load static %}


{% block title %}
<title>Clientes</title>
{% endblock title %}

{% block nombre_seccion %}
<p class="header__titulo letra_blanca">Menú Clientes</p>
{% endblock nombre_seccion %}

{% block boton_volver %}
<li>
    <a href="{% url "menu_opciones" %}" class="header__boton header__volver">
        <img src="{% static "images/logo_volver.png" %}" alt="volver" class="header__logo_boton">
    </a>
</li>
{% endblock boton_volver %}

{% block boton_registrar %}
<li>
    {% include "layouts/partials/boton_registrar.html" %}
</li>
{% endblock boton_registrar %}

{% block boton_buscar %}
<li>
    {% include "layouts/partials/boton_buscar.html" %}
</li>
{% include "layouts/modals/modals_clientes/buscador_clientes.html" %}
{% endblock boton_buscar %}

{% block boton_cerrar_sesion %}
    {% include "layouts/partials/boton_cerrar_sesion.html" %}
{% endblock boton_cerrar_sesion %}

{% block cuerpo_seccion %}
{% include "layouts/modals/mensajes/confirmar_eliminar.html" %}
{% include "layouts/modals/modals_clientes/registrar_clientes.html" %}
{% include "layouts/modals/modals_clientes/editar_clientes.html" %}
{% include "layouts/modals/mensajes/mensaje_input_no_valido.html" %}

{% if registrado %}
    {% include "layouts/modals/mensajes/mensaje_registrado.html" %}
{% endif %}
{% if actualizado %}
    {% include "layouts/modals/mensajes/mensaje_actualizado.html" %}
{% endif %}
{% if eliminado %}
    {% include "layouts/modals/mensajes/mensaje_eliminacion.html" %}
{% endif %}
{% if actualizado %}
    {% include "layouts/modals/mensajes/mensaje_actualizado.html" %}
{% endif %}
{% if sin_coincidencias %}
    {% include "layouts/modals/mensajes/mensaje_sin_coincidencias.html" %}
{% endif %}
{% if error %}
    {% include "layouts/modals/mensajes/mensaje_error.html" %}
{% endif %}



<div class="contenedor tabla_registros">
    <table class="tabla_registros__tabla">
        <tr class="celdas_encabezado">
            <th class="celda tabla_registros__celda_id">ID</th>
            <th class="celda tabla_registros__celda_nombre">Nombre</th>
            <th class="celda tabla_registros__celda_numero_di">Número DI</th>
            <th class="celda tabla_registros__celda_correo">Correo</th>
            <th class="celda tabla_registros__celda_telefono">Teléfono</th>
            <th colspan="2" class="celda tabla_registros__celda_recargar"><a href="{% url "clientes" %}"><img src="{% static "images/logo_recargar.png" %}" alt="recargar" class="tabla_registros__recargar"></a></th>
        </tr>
        {% for cliente in pagina.object_list %}
        <tr class="celdas_datos">
            <td class="celda tabla_registros__celda_id">{{ cliente.id }}</td>
            <td class="celda tabla_registros__celda_nombre">{{ cliente.nombre_cliente }}</td>
            <td class="celda tabla_registros__celda_numero_di">{{ cliente.documento_identidad }}</td>
            <td class="celda tabla_registros__celda_correo">{{ cliente.correo_electronico }}</td>
            <td class="celda tabla_registros__celda_telefono">{{ cliente.telefono }}</td>
            <td class="celda tabla_registros__celda_editar"><a href="#" data-registro-id={{ cliente.id }} data-app-registro="clientes" class="tabla_registros__boton boton_editar" ><img src="{% static "images/logo_editar.png" %}" alt="editar" class="tabla_registros__logo_boton tabla_registros__editar"></a></td>
            <td class="celda tabla_registros__celda_eliminar"><a href="#" data-url= {% url "eliminar_cliente" cliente.id %} data-mensaje= "cliente {{ cliente.nombre_cliente }} con ID {{ cliente.id }}" class="tabla_registros__boton boton_eliminar"><img src="{% static "images/logo_eliminar.png" %}" alt="eliminar" class="tabla_registros__logo_boton tabla_registros__eliminar"></a></td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock cuerpo_seccion %}
{% block paginacion %}
{% include "layouts/partials/paginacion.html" %}
{% endblock paginacion %}

SoftwareTaller/templates/ingreso.html
{% extends "layouts/base.html" %}

{% block script %}{% endblock script %}
{% block title %}
<title>Ingreso</title>
{% endblock title %}

{% block header %}
{% endblock header %}


    {% block titulo_en_encabezado %}{% endblock titulo_en_encabezado %}

    {% block titulo_en_cuerpo %}
    {% include "layouts/partials/titulo.html" %}
    {% endblock titulo_en_cuerpo %}
    {% block navegacion_secciones %}{% endblock navegacion_secciones %}
    {% block cuerpo_seccion %}
    {% if credenciales_equivocadas %}
        {% include "layouts/modals/mensajes/mensaje_credenciales_equivocadas.html" %}
    {% endif %}
    <body class="body_ingreso">
        {% include "forms/form_ingreso.html" %}
    </body>
    {% endblock cuerpo_seccion %}

SoftwareTaller/templates/menu_opciones.html
{% extends "layouts/base.html" %}
{% load static %}
{% block script %}{% endblock script %}
{% block title %}
<title>Inicio</title>
{% endblock title %}

{% block nombre_seccion %}
<p class="header__titulo letra_blanca">Menú de Inicio</p>
{% endblock nombre_seccion %}

{% block titulo_en_encabezado %}{% endblock titulo_en_encabezado %}

{% block boton_cerrar_sesion %}
    {% include "layouts/partials/boton_cerrar_sesion.html" %}
{% endblock boton_cerrar_sesion %}


{% block titulo_en_cuerpo %}
{% include "layouts/partials/titulo.html" %}
{% endblock titulo_en_cuerpo %}
{% block navegacion_secciones %}{% endblock navegacion_secciones %}
{% block cuerpo_seccion %}
<div class="contenedor menu_opciones">
    <a href="{% url 'clientes' %}" class="menu_opciones__opcion letra_negra">
        <figure class="menu_opciones__tarjeta">
            <img src="{% static "images/logo_cliente.png" %}" alt="clientes" class="menu_opciones__logo_cliente">
            <figcaption>
                <h2>Clientes</h2>
            </figcaption>
        </figure>
    </a>
    <a href="{% url "inventario" %}" class="menu_opciones__opcion letra_negra">
        <figure class="menu_opciones__tarjeta">
            <img src="{% static "images/logo_inventario.png" %}" alt="inventario" class="menu_opciones__logo_inventario">
            <figcaption>
                <h2>Inventario</h2>
            </figcaption>
        </figure>
    </a>
    <a href="{% url "servicios" %}" class="menu_opciones__opcion letra_negra">
        <figure class="menu_opciones__tarjeta">
            <img src="{% static "images/logo_servicios.png" %}" alt="servicios" class="menu_opciones__logo_inventario">
            <figcaption>
                <h2>Servicios</h2>
            </figcaption>
        </figure>
    </a>
</div>
<p class="letra_roja parrafo">Selecciona la tarjeta de la sección a la que deseas dirigirte</p>
{% endblock cuerpo_seccion %}

SoftwareTaller/templates/servicios.html
{% extends "layouts/base.html" %}
{% load static %}


{% block title %}
<title>Servicios</title>
{% endblock title %}

{% block nombre_seccion %}
<p class="header__titulo letra_blanca">Menú Servicios</p>
{% endblock nombre_seccion %}

{% block boton_volver %}
<li>
    <a href="{% url "menu_opciones" %}" class="header__boton header__volver">
        <img src="{% static "images/logo_volver.png" %}" alt="volver" class="header__logo_boton">
    </a>
</li>
{% endblock boton_volver %}

{% block boton_registrar %}
<li>
    {% include "layouts/partials/boton_registrar.html" %}
</li>
{% endblock boton_registrar %}

{% block boton_buscar %}
<li>
    {% include "layouts/partials/boton_buscar.html" %}
</li>
{% include "layouts/modals/modals_servicios/buscador_servicios.html" %}
{% endblock boton_buscar %}

{% block boton_cerrar_sesion %}
    {% include "layouts/partials/boton_cerrar_sesion.html" %}
{% endblock boton_cerrar_sesion %}

{% block cuerpo_seccion %}
{% include "layouts/modals/mensajes/confirmar_eliminar.html" %}
{% include "layouts/modals/modals_servicios/registrar_servicios.html" %}
{% include "layouts/modals/modals_servicios/editar_servicios.html" %}
{% include "layouts/modals/modals_servicios/servicio_asignar_cliente.html" %}
{% include "layouts/modals/modals_servicios/servicio_asignar_productos.html" %}
{% include "layouts/modals/mensajes/mensaje_cantidad_no_valida.html" %}
{% include "layouts/modals/mensajes/mensaje_input_no_valido.html" %}
{% if registrado %}
    {% include "layouts/modals/mensajes/mensaje_registrado.html" %}
{% endif %}
{% if eliminado %}
    {% include "layouts/modals/mensajes/mensaje_eliminacion.html" %}
{% endif %}
{% if actualizado %}
    {% include "layouts/modals/mensajes/mensaje_actualizado.html" %}
{% endif %}
{% if sin_coincidencias %}
    {% include "layouts/modals/mensajes/mensaje_sin_coincidencias.html" %}
{% endif %}
{% if error %}
    {% include "layouts/modals/mensajes/mensaje_error.html" %}
{% endif %}


<div id="nombres_servicios" style="display: none;">{{ lista_nombres_servicios | json_script:"nombresServicios" }}</div>

<div class="contenedor tabla_registros">
    <table class="tabla_registros__tabla">
        <tr class="celdas_encabezado">
            <th class="celda tabla_registros__celda_id">ID</th>
            <th class="celda tabla_registros__celda_servicio">Servicio</th>
            <th class="celda tabla_registros__celda_descripcion">Descripción</th>
            <th class="celda tabla_registros__celda_costo_total">Costo</th>
            <th class="celda tabla_registros__celda_fecha">Fecha</th>
            <th class="celda tabla_registros__celda_info_cliente">ID.Cliente</th>
            <th class="celda tabla_registros__celda_productos">Productos</th>
            <th colspan="2" class="celda tabla_registros__celda_recargar"><a href="{% url "servicios" %}"><img src="{% static "images/logo_recargar.png" %}" alt="recargar" class="tabla_registros__recargar"></a></th>
        </tr>
        {% for servicio in pagina.object_list %}
        <tr class="celdas_datos">
            <td class="celda tabla_registros__celda_id">{{ servicio.id }}</td>
            <td class="celda tabla_registros__celda_servicio">{{ servicio.nombre_servicio.nombre_servicio }}</td>
            <td class="celda tabla_registros__celda_descripcion">{{ servicio.descripcion }}</td>
            <td class="celda tabla_registros__celda_costo_total">{{ servicio.costo_total }}</td>
            <td class="celda tabla_registros__celda_fecha">{{ servicio.fecha }}</td>
            <td class="celda tabla_registros__celda_info_cliente">{{ servicio.cliente.id }}. {{ servicio.cliente.nombre_cliente }}</td>
            <td class="celda tabla_registros__celda_productos">
                <div class="tabla_registros__contenedor_lista_productos">
                    <ul class="tabla_registros__lista_productos">
                        {% for registro in servicio.servicio_productos_set.all %}
                        <li>{{ registro.producto.referencia }} ({{ registro.cantidad }})</li>
                        {% endfor %}
                    </ul>
                </div>
            </td>
            <td class="celda tabla_registros__celda_editar"><a href="#" data-registro-id={{ servicio.id }} data-app-registro="servicios" class="tabla_registros__boton boton_editar"><img src="{% static "images/logo_editar.png" %}" alt="editar" class="tabla_registros__logo_boton tabla_registros__editar"></a></td>
            <td class="celda tabla_registros__celda_eliminar"><a href="#" data-url= {% url "eliminar_servicio" servicio.id %} data-mensaje= "Servicio  {{ servicio.nombre_servicio.nombre_servicio }} con ID {{ servicio.id }} realizado al cliente {{ servicio.cliente.nombre_cliente }}" class="tabla_registros__boton boton_eliminar"><img src="{% static "images/logo_eliminar.png" %}" alt="eliminar" class="tabla_registros__logo_boton tabla_registros__eliminar"></a></td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock cuerpo_seccion %}
{% block paginacion %}
{% include "layouts/partials/paginacion.html" %}
{% endblock paginacion %}